import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://filevisualizer.tiiny.site/');
  await page.locator('#file1').click();
  await page.locator('#file1').setInputFiles('cdifferent copy.cpp');
  await page.locator('#file2').click();
  await expect(page.getByText('cdifferent copy.cpp')).toBeVisible();
  await page.locator('#file2').setInputFiles('calculator copy.cpp');
  await page.getByRole('button', { name: 'Compare Files' }).click();
  await page.getByText('cdifferent copy.cpp /* Name: CALCULATOR v1.0 Author: Aldo Ziflaj Date: 01-01-13 ').click();
  await page.getByText('#include #include #include #include using namespace std; int bookAppointment() {').click();
  await page.locator('#file1').click();
  await page.locator('#file2').click();
  await page.locator('#file2').setInputFiles('cdifferent copy.cpp');
  await page.getByRole('button', { name: 'Compare Files' }).click();
  await page.getByRole('cell', { name: 'raise to n-th integer power and calculate the factorial' }).first().click();
  await page.getByRole('cell', { name: 'Date: 01-01-13 12:01' }).nth(1).click();
  await page.locator('#file1TableName').click();
  await page.getByRole('row', { name: '10 #include #include' }).getByRole('cell', { name: '#include' }).nth(1).click();
  await page.getByRole('cell', { name: 'using namespace std;' }).first().click();
  await page.getByRole('cell', { name: 'cin>>a; // 1ST NUMBER' }).first().click();
  await page.getByRole('cell', { name: 'cin>>a; // 1ST NUMBER' }).nth(1).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Report' }).click();
  const download = await downloadPromise;
  await expect(downloadButton).toBeVisible();
  await page.getByRole('cell', { name: '/*' }).first().click();
  await page.getByRole('cell', { name: '/*' }).nth(1).click();
  await page.getByRole('cell', { name: 'Name: CALCULATOR v1.0' }).first().click();
  await page.getByRole('cell', { name: 'Name: CALCULATOR v1.0' }).nth(1).click();
  await page.getByRole('cell', { name: 'Author: Aldo Ziflaj' }).first().click();
  await page.getByRole('cell', { name: 'Author: Aldo Ziflaj' }).nth(1).click();
  await page.locator('#file1').click();
  await page.locator('#file1').setInputFiles('calculator copy.cpp');
  await page.locator('#file2').click();
  await page.getByRole('button', { name: 'Compare Files' }).click();
  await page.getByRole('row', { name: '1 #include /*' }).getByRole('cell', { name: '#include' }).click();
  await page.getByRole('cell', { name: '/*' }).click();
  await page.getByRole('row', { name: '2 #include Name: CALCULATOR v1.0' }).getByRole('cell', { name: '#include' }).click();
  await page.getByRole('cell', { name: 'Name: CALCULATOR v1.0' }).click();
  await page.getByRole('row', { name: '3 #include Author: Aldo Ziflaj' }).getByRole('cell', { name: '#include' }).click();
  await page.getByRole('cell', { name: 'Author: Aldo Ziflaj' }).click();
  await page.getByRole('row', { name: '4 #include Date: 01-01-13 12:01' }).getByRole('cell', { name: '#include' }).click();
  await page.getByRole('cell', { name: 'Date: 01-01-13 12:01' }).click();
  await page.getByRole('cell', { name: '/*' }).click();
  await page.getByRole('row', { name: '1 #include /*' }).getByRole('cell', { name: '#include' }).click();
  await page.getByRole('row', { name: '5 using namespace std; Description: A simple calculator that can add, subtract multiply, divide,' }).getByRole('cell', { name: 'using namespace std;' }).click();
  await page.getByRole('cell', { name: 'double a,b,r,memory=0;' }).click();
  await page.getByRole('row', { name: '19 string line; double a,b,r,memory=0;' }).getByRole('cell', { name: 'string line;' }).click();
  await page.getByRole('cell', { name: 'cout<<"+ to add, - to subtract, * to multiply, / to divide, \\' }).click();
  await page.getByRole('row', { name: '22 while(getline(read, line)) { ^ to power, ! to factorial\\n\\n";' }).getByRole('cell', { name: 'while(getline(read, line)) {' }).click();
  await page.getByRole('row', { name: '30 cout<<"\\n Appointment Summary by hours:"; cin>>b;' }).getByRole('cell', { name: 'cout<<"\\n Appointment Summary by hours:";' }).click();
  await page.getByRole('cell', { name: 'cin>>b;' }).click();
  await page.getByRole('cell', { name: '33', exact: true }).click();
  await page.getByRole('cell', { name: '38', exact: true }).click();
  await page.getByRole('row', { name: '38 else cout<<"="<' }).getByRole('cell', { name: 'else' }).click();
  await page.getByRole('cell', { name: 'cout<<"="<' }).click();
});
